name: watch_security_bot
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.10.0
          pip install requests==2.23.0
      - name: Run script
        run: |
          FROM_ADDRESS=${{secrets.FROM_ADDRESS}}
          PASSWORD=${{secrets.PASSWORD}}
          TO_ADDRESS=${{secrets.TO_ADDRESS}}
          python main.py
