name: watch_security_bot
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4==4.10.0
          pip install requests==2.23.0
      - name: Run script
        env:
          FROM_ADDRESS: ${{ secrets.FROM_ADDRESS }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TO_ADDRESS: ${{ secrets.TO_ADDRESS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $FROM_ADDRESS
          echo $GITHUB_TOKEN
          python main.py
